# Generated by Django 5.0.5 on 2024-05-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='full_text',
        ),
    ]
